/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

_If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.11
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type {
  PetDTO,
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  UpdatePetWithFormParams,
  ApiResponseDTO,
  UploadFileParams,
  GetInventory200,
  OrderDTO,
  UserDTO,
  LoginUserParams,
} from "./swagger.schemas";

export const getApi = () => {
  /**
   * Update an existing pet by Id
   * @summary Update an existing pet
   */
  const updatePet = <TData = AxiosResponse<PetDTO>>(
    petDTO: PetDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.put(`/pet`, petDTO, options);
  };

  /**
   * Add a new pet to the store
   * @summary Add a new pet to the store
   */
  const addPet = <TData = AxiosResponse<PetDTO>>(
    petDTO: PetDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/pet`, petDTO, options);
  };

  /**
   * Multiple status values can be provided with comma separated strings
   * @summary Finds Pets by status
   */
  const findPetsByStatus = <TData = AxiosResponse<PetDTO[]>>(
    params?: FindPetsByStatusParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/pet/findByStatus`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   * @summary Finds Pets by tags
   */
  const findPetsByTags = <TData = AxiosResponse<PetDTO[]>>(
    params?: FindPetsByTagsParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/pet/findByTags`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Returns a single pet
   * @summary Find pet by ID
   */
  const getPetById = <TData = AxiosResponse<PetDTO>>(
    petId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/pet/${petId}`, options);
  };

  /**
   * @summary Updates a pet in the store with form data
   */
  const updatePetWithForm = <TData = AxiosResponse<unknown>>(
    petId: number,
    params?: UpdatePetWithFormParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/pet/${petId}`, undefined, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * delete a pet
   * @summary Deletes a pet
   */
  const deletePet = <TData = AxiosResponse<unknown>>(
    petId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.delete(`/pet/${petId}`, options);
  };

  /**
   * @summary uploads an image
   */
  const uploadFile = <TData = AxiosResponse<ApiResponseDTO>>(
    petId: number,
    uploadFileBodies: Blob,
    params?: UploadFileParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/pet/${petId}/uploadImage`, uploadFileBodies, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * Returns a map of status codes to quantities
   * @summary Returns pet inventories by status
   */
  const getInventory = <TData = AxiosResponse<GetInventory200>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/store/inventory`, options);
  };

  /**
   * Place a new order in the store
   * @summary Place an order for a pet
   */
  const placeOrder = <TData = AxiosResponse<OrderDTO>>(
    orderDTO: OrderDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/store/order`, orderDTO, options);
  };

  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   * @summary Find purchase order by ID
   */
  const getOrderById = <TData = AxiosResponse<OrderDTO>>(
    orderId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/store/order/${orderId}`, options);
  };

  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   * @summary Delete purchase order by ID
   */
  const deleteOrder = <TData = AxiosResponse<unknown>>(
    orderId: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.delete(`/store/order/${orderId}`, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Create user
   */
  const createUser = <TData = AxiosResponse<unknown>>(
    userDTO: UserDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/user`, userDTO, options);
  };

  /**
   * Creates list of users with given input array
   * @summary Creates list of users with given input array
   */
  const createUsersWithListInput = <TData = AxiosResponse<UserDTO>>(
    userDTO: UserDTO[],
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`/user/createWithList`, userDTO, options);
  };

  /**
   * @summary Logs user into the system
   */
  const loginUser = <TData = AxiosResponse<string>>(
    params?: LoginUserParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/user/login`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  /**
   * @summary Logs out current logged in user session
   */
  const logoutUser = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/user/logout`, options);
  };

  /**
   * @summary Get user by user name
   */
  const getUserByName = <TData = AxiosResponse<UserDTO>>(
    username: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`/user/${username}`, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Update user
   */
  const updateUser = <TData = AxiosResponse<unknown>>(
    username: string,
    userDTO: UserDTO,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.put(`/user/${username}`, userDTO, options);
  };

  /**
   * This can only be done by the logged in user.
   * @summary Delete user
   */
  const deleteUser = <TData = AxiosResponse<unknown>>(
    username: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.delete(`/user/${username}`, options);
  };

  return {
    updatePet,
    addPet,
    findPetsByStatus,
    findPetsByTags,
    getPetById,
    updatePetWithForm,
    deletePet,
    uploadFile,
    getInventory,
    placeOrder,
    getOrderById,
    deleteOrder,
    createUser,
    createUsersWithListInput,
    loginUser,
    logoutUser,
    getUserByName,
    updateUser,
    deleteUser,
  };
};
export type UpdatePetResult = AxiosResponse<PetDTO>;
export type AddPetResult = AxiosResponse<PetDTO>;
export type FindPetsByStatusResult = AxiosResponse<PetDTO[]>;
export type FindPetsByTagsResult = AxiosResponse<PetDTO[]>;
export type GetPetByIdResult = AxiosResponse<PetDTO>;
export type UpdatePetWithFormResult = AxiosResponse<unknown>;
export type DeletePetResult = AxiosResponse<unknown>;
export type UploadFileResult = AxiosResponse<ApiResponseDTO>;
export type GetInventoryResult = AxiosResponse<GetInventory200>;
export type PlaceOrderResult = AxiosResponse<OrderDTO>;
export type GetOrderByIdResult = AxiosResponse<OrderDTO>;
export type DeleteOrderResult = AxiosResponse<unknown>;
export type CreateUserResult = AxiosResponse<unknown>;
export type CreateUsersWithListInputResult = AxiosResponse<UserDTO>;
export type LoginUserResult = AxiosResponse<string>;
export type LogoutUserResult = AxiosResponse<unknown>;
export type GetUserByNameResult = AxiosResponse<UserDTO>;
export type UpdateUserResult = AxiosResponse<unknown>;
export type DeleteUserResult = AxiosResponse<unknown>;
